with generated_names(name) as (
  values
  ('Apigenin (Chamomile Extract)'),
  ('Apple Cider Vinegar (ACV)'),
  ('Ashwagandha (Withania somnifera)'),
  ('Astaxanthin'),
  ('Bacopa Monnieri'),
  ('B Complex Vitamins'),
  ('BCAAs (Branched-Chain Amino Acids)'),
  ('Beetroot Juice (Dietary Nitrates)'),
  ('Berberine'),
  ('Beta-Glucans'),
  ('Biotin (Vitamin B7)'),
  ('Black Currant Seed Oil'),
  ('Black Seed Oil'),
  ('Boswellia (Boswellia serrata)'),
  ('BPC-157'),
  ('Bromelain'),
  ('Butcher''s Broom (Ruscus aculeatus)'),
  ('Caffeine'),
  ('Calcium'),
  ('Capsaicin'),
  ('Casein Protein'),
  ('CBD (Cannabidiol)'),
  ('Chlorogenic Acid / Green Coffee Bean Extract'),
  ('Chondroitin'),
  ('Chromium Picolinate'),
  ('Cinnamon Extract'),
  ('Citicoline (CDP-Choline)'),
  ('Citrulline Malate'),
  ('Coconut Oil'),
  ('Coenzyme Q10 (Ubiquinol)'),
  ('Collagen Peptides (Hydrolysed Collagen)'),
  ('Conjugated Linoleic Acid (CLA)'),
  ('Cordyceps (Cordyceps sinensis)'),
  ('Cranberry Extract'),
  ('Creatine / Creatine Monohydrate'),
  ('Curcumin (Turmeric Extract)'),
  ('D-Aspartic Acid (DAA)'),
  ('D-Mannose'),
  ('DIM (Diindolylmethane)'),
  ('Echinacea'),
  ('Elderberry'),
  ('Evening Primrose Oil'),
  ('Fenugreek'),
  ('Fisetin'),
  ('Folate (Vitamin B9)'),
  ('Garcinia Cambogia'),
  ('Garlic Extract (Aged Garlic Extract)'),
  ('Ginger'),
  ('Ginkgo Biloba'),
  ('Glucomannan'),
  ('Glucosamine sulphate'),
  ('Glycine'),
  ('Gotu Kola'),
  ('Green Tea Extract'),
  ('Gymnema Sylvestre Extract'),
  ('Hibiscus Extract'),
  ('HMB (Beta-Hydroxy Beta-Methylbutyrate)'),
  ('Horse Chestnut Seed Extract'),
  ('Hyaluronic Acid (Oral)'),
  ('Inositol (Myo-Inositol, D-Chiro-Inositol)'),
  ('Iodine'),
  ('Iron'),
  ('L-Arginine'),
  ('L-Carnitine'),
  ('L-Citrulline'),
  ('L-Glutamine'),
  ('L-Theanine'),
  ('Lion''s Mane'),
  ('Maca Root'),
  ('Magnesium (Glycinate & L-Threonate)'),
  ('Melatonin (Prescription Medication in UK)'),
  ('Melilotus (Sweet Clover) Extract'),
  ('Methylene Blue'),
  ('Milk Thistle'),
  ('MSM (Methylsulfonylmethane)'),
  ('Neem Oil / Neem Leaf Extract'),
  ('Nettle Root'),
  ('Nicotinamide Riboside / Niacinamide / Niacin (B3)'),
  ('NMN (Nicotinamide Mononucleotide)'),
  ('Omega-3'),
  ('Panax Ginseng'),
  ('Phosphate'),
  ('Phosphatidylcholine (Choline)'),
  ('Phosphatidylserine (PS)'),
  ('Phytoestrogens'),
  ('Plant Protein'),
  ('Polypodium Leucotomos Extract (PLE)'),
  ('Potassium'),
  ('Prebiotics'),
  ('Probiotics'),
  ('Psyllium Husk'),
  ('Pterostilbene'),
  ('Pumpkin Seed Oil'),
  ('Pycnogenol'),
  ('Pyrroloquinoline Quinone (PQQ)'),
  ('Quercetin'),
  ('Raspberry Ketones'),
  ('Resveratrol (Japanese Knotweed)'),
  ('Rhodiola Rosea'),
  ('Saffron Extract'),
  ('SAMe (S-Adenosylmethionine)'),
  ('Saw Palmetto'),
  ('Sea Moss'),
  ('Selenium'),
  ('Shilajit'),
  ('Soy Isoflavones (Genistein and Daidzein)'),
  ('Spermidine'),
  ('Spirulina'),
  ('St. John''s Wort (Hypericum perforatum)'),
  ('Sterols'),
  ('Strontium'),
  ('Taurine'),
  ('Thiamine'),
  ('Tongkat Ali (Eurycoma longifolia)'),
  ('Tribulus Terrestris'),
  ('Urolithin A'),
  ('Valerian Root (Valeriana officinalis)'),
  ('Vitamin B12 (Cobalamin)'),
  ('Vitamin C (Ascorbic Acid)'),
  ('Vitamin D / D3/ Cholecalciferol'),
  ('Vitamin E / Tocotrienols'),
  ('Vitamin K'),
  ('Vitex Agnus-Castus (Chasteberry)'),
  ('Whey Protein'),
  ('Yohimbine'),
  ('Zinc')
)
select g.name
from generated_names g
left join public.supplements s
  on s.name = g.name
 and s.status = 'approved'
where s.id is null
order by g.name;
