with generated_names(name) as (
  values
  ('Apigenin / Chamomile Extract'),
  ('Apple Cider Vinegar (ACV)'),
  ('Ashwagandha (Withania somnifera)'),
  ('Astaxanthin'),
  ('Bacopa monnieri'),
  ('B Complex Vitamins'),
  ('Branched-Chain Amino Acids (BCAAs)'),
  ('Beetroot Juice (Dietary Nitrates)'),
  ('Berberine'),
  ('Beta-Glucans'),
  ('Biotin (Vitamin B7)'),
  ('Black Currant Seed Oil (Ribes nigrum)'),
  ('Black Seed Oil (Nigella sativa)'),
  ('Boswellia serrata'),
  ('BPC-157'),
  ('Bromelain'),
  ('Butcher’s Broom (Ruscus aculeatus)'),
  ('Caffeine'),
  ('Calcium'),
  ('Capsaicin'),
  ('Casein Protein'),
  ('CBD (Cannabidiol)'),
  ('Chlorogenic Acid / Green Coffee Bean'),
  ('Chondroitin'),
  ('Chromium Picolinate'),
  ('Cinnamon Extract'),
  ('Citicoline (CDP-Choline)'),
  ('Citrulline Malate'),
  ('Coconut oil'),
  ('Coenzyme Q10 (CoQ10) / Ubiquinol'),
  ('Collagen Peptides (Hydrolyzed Collagen)'),
  ('Conjugated linoleic acid (CLA)'),
  ('Cordyceps (Cordyceps sinensis)'),
  ('Cranberry Extract'),
  ('Creatine / Creatine Monohydrate'),
  ('Curcumin / Turmeric extract'),
  ('D-Aspartic Acid (DAA)'),
  ('D-Mannose'),
  ('Diindolylmethane (DIM)'),
  ('Echinacea'),
  ('Elderberry'),
  ('Evening primrose oil'),
  ('Fenugreek'),
  ('Fisetin'),
  ('Folate (vitamin B9)'),
  ('Garcinia extract (hydroxycitric acid)'),
  ('Garlic extract (aged garlic extract)'),
  ('Ginger'),
  ('Ginkgo biloba'),
  ('Glucomannan'),
  ('Glucosamine'),
  ('Glycine'),
  ('Gotu kola (Centella asiatica)'),
  ('Green tea extract / EGCG'),
  ('Gymnema sylvestre extract'),
  ('Hibiscus extract'),
  ('Beta-hydroxy beta-methylbutyrate (HMB)'),
  ('Horse chestnut seed extract'),
  ('Oral hyaluronic acid'),
  ('Inositol (Myo-Inositol / D-Chiro-Inositol)'),
  ('Iodine'),
  ('Iron'),
  ('L-Arginine'),
  ('L-Carnitine'),
  ('L-Citrulline'),
  ('L-Glutamine'),
  ('L-Theanine'),
  ('Lion’s mane mushroom'),
  ('Maca root'),
  ('Magnesium'),
  ('Melatonin'),
  ('Melilotus (Sweet Clover) Extract'),
  ('Methylene blue'),
  ('Milk thistle'),
  ('Methylsulfonylmethane (MSM)'),
  ('Neem Oil (Azadirachta indica)'),
  ('Nettle root'),
  ('Niacinamide / Nicotinamide / Niacin (Vitamin B3)'),
  ('Nicotinamide mononucleotide (NMN)'),
  ('Omega-3 fatty acids'),
  ('Panax ginseng'),
  ('Phosphate'),
  ('Phosphatidylcholine (choline)'),
  ('Phosphatidylserine (PS)'),
  ('Phytoestrogens'),
  ('Plant protein'),
  ('Polypodium leucotomos extract (PLE)'),
  ('Potassium'),
  ('Prebiotics'),
  ('Probiotics'),
  ('Psyllium husk'),
  ('Pterostilbene'),
  ('Pumpkin seed oil'),
  ('Pycnogenol'),
  ('Pyrroloquinoline Quinone (PQQ)'),
  ('Quercetin'),
  ('Raspberry Ketones'),
  ('Resveratrol (Japanese Knotweed)'),
  ('Rhodiola rosea'),
  ('Saffron'),
  ('SAMe (S-adenosylmethionine)'),
  ('Saw palmetto'),
  ('Sea Moss (Chondrus crispus)'),
  ('Selenium'),
  ('Shilajit'),
  ('Soy isoflavones (Genistein and Daidzein)'),
  ('Spermidine'),
  ('Spirulina (Arthrospira platensis)'),
  ('St. John’s wort (Hypericum perforatum)'),
  ('Sterols'),
  ('Strontium'),
  ('Taurine'),
  ('Thiamine'),
  ('Tongkat Ali (Eurycoma longifolia)'),
  ('Tribulus terrestris'),
  ('Urolithin A'),
  ('Valerian Root (Valeriana officinalis)'),
  ('Vitamin B12 (Cobalamin)'),
  ('Vitamin C (Ascorbic acid)'),
  ('Vitamin D / D3 / Cholecalciferol'),
  ('Vitamin E (Tocopherols and Tocotrienols)'),
  ('Vitamin K'),
  ('Vitex agnus-castus (Chasteberry)'),
  ('Whey Protein'),
  ('Yohimbine'),
  ('Zinc')
)
select g.name
from generated_names g
left join public.supplements s
  on s.name = g.name
 and s.status = 'approved'
where s.id is null
order by g.name;
